image: amazoncorretto:21-alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - merge
  - build
  - deploy

#TODO add client reference test process, search for import com.cobblemon.mod.common.client

build:
  stage: build
  only:
    - branches@cable-mc/cobblemon
  script:
    - export GRADLE_OPTS="-Xmx4G -Xms4G"
    - chmod +x ./gradlew
    - ./gradlew build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - neoforge/build/libs
      - fabric/build/libs

publish:
  stage: deploy
  dependencies:
    - build
  cache:
    key: "CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - neoforge/build/libs/*.jar
      - fabric/build/libs/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - export GRADLE_OPTS="-Xmx4G -Xms4G"
    - chmod +x ./gradlew
    - ./gradlew publish

# Separate step to deploy the artifacts, save Norry the headache of keeping even more shit around
deploy:
  stage: deploy
  dependencies:
    - build
  when: manual
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - neoforge/build/libs/*.jar
      - fabric/build/libs/*.jar
  script: 
    - echo "Collecting artifacts..."
    - mv neoforge/build/libs/*+*.jar ./
    - mv fabric/build/libs/*+*.jar ./
    - for f in *.jar; do mv "$f" "$(echo "$f" | sed s/+/b$CI_PIPELINE_IID+/)"; done
  artifacts:
    expire_in: 28 days
    paths:
      - ./*.jar
#      - neoforge/build/libs/*+*.jar
#      - fabric/build/libs/*+*.jar

merge_on_lang_change:
  stage: merge
  script:
    # Check for changes in the specified file or directory
    - |
      apk add git
      if git diff --name-only "$CI_COMMIT_BEFORE_SHA" "$CI_COMMIT_SHA" | grep -q "common/src/main/resources/assets/cobblemon/lang/en_us.json"; then
        echo "US locale changed! Updating lang branch..."
      
        # Configure Git user for the merge commit
        git config --global user.email "noreply@weblate.org"
        git config --global user.name "Weblate"
        git remote set-url origin https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/cable-mc/cobblemon.git
      
        # Fetch the target branch and merge main into it
        git fetch origin lang-updates
        git checkout lang-updates
        git merge main
      
        # Push the merged branch back to the repository
        git push origin lang-updates-test
      else
        echo "No need to update lang"
      fi
  only:
    - ci-test
